name: Deploy LOVE2D Game to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create publish directory
        run: mkdir -p publish

      - name: Clone love.js
        run: git clone https://github.com/Davidobot/love.js.git

      - name: Verify love.js files exist
        run: |
          if [ ! -f "love.js/src/game.js" ]; then
            echo "Error: love.js/src/game.js is missing"
            exit 1
          fi
          ls -l love.js/src/game.js

      - name: Copy love.js files
        run: |
          # Copy the release files instead of src
          cp -r love.js/src/release/* publish/
          # Ensure we have the right files
          if [ ! -f "publish/love.js" ]; then
            echo "Error: love.js is missing from release directory"
            exit 1
          fi

      - name: Zip game files into game.love
        run: |
          # Only include game files
          zip -r publish/game.love \
            main.lua \
            conf.lua \
            *.png \
            *.wav \
            *.mp3 \
            *.ogg \
            -x "love.js/*" \
            -x ".git/*" \
            -x ".github/*"

      - name: Create index.html
        run: |
          cat > publish/index.html <<EOF
          <!doctype html>
          <html lang="en-us">
            <head>
              <meta charset="utf-8">
              <title>Caterpillar Quest</title>
              <style>
                body { margin: 0; background: black; }
                canvas { 
                  position: absolute;
                  top: 50%;
                  left: 50%;
                  transform: translate(-50%, -50%);
                  width: 1024px;
                  height: 768px;
                  max-width: 100%;
                  max-height: 100vh;
                }
              </style>
            </head>
            <body>
              <canvas id="canvas"></canvas>
              <script>
                var Module = {};
                Module.canvas = document.getElementById('canvas');
              </script>
              <script async type="text/javascript" src="love.js"></script>
            </body>
          </html>
          EOF

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GH_PAT }}
          publish_dir: ./publish