name: Deploy LOVE2D Game to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get short commit hash
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Create publish directory
        run: mkdir publish

      - name: Zip game files into game.love
        run: zip -r publish/game.love . -x ".git/*" ".github/*"

      - name: Clone love.js
        run: git clone https://github.com/Davidobot/love.js.git

      - name: Copy love.js engine files
        run: cp -r love.js/src/* publish/

      - name: Create index.html with cache busting
        run: |
          cat > publish/index.html <<EOF
          <!DOCTYPE html>
          <html>
          <head>
            <meta charset="utf-8">
            <title>Caterpillar Quest</title>
            <style>
              body { margin: 0; padding: 0; background-color: #000; }
              canvas { display: block; margin: auto; }
            </style>
            <script>
              var Module = {
                TOTAL_MEMORY: 268435456,
                errorhandler: null,
                compatibilitycheck: null,
                dataFileDownloads: {},
                arguments: ['./game.love'],
                printErr: function(text) { console.error(text); },
                canvas: (function() {
                  var canvas = document.createElement('canvas');
                  canvas.addEventListener("webglcontextlost", function(e) {
                    alert('WebGL context lost. You will need to reload the page.');
                    e.preventDefault();
                  }, false);
                  return canvas;
                })(),
                setStatus: function(text) { console.log(text); },
                monitorRunDependencies: function(left) {}
              };
            </script>
          </head>
          <body>
            <script async type="text/javascript" src="game.js?v=${{ steps.vars.outputs.sha_short }}"></script>
          </body>
          </html>
          EOF

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GH_PAT }}
          publish_dir: ./publish