name: Deploy LOVE2D Game to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create publish directory
        run: mkdir publish

      - name: Zip game files into game.love
        run: zip -r publish/game.love . -x ".git/*" ".github/*"

      - name: Clone love.js
        run: git clone https://github.com/Davidobot/love.js.git

      - name: Copy love.js files
        run: |
          cp -r love.js/src/compat publish/
          cp -r love.js/src/release publish/
          cp love.js/src/game.js publish/

      - name: Create index.html
        run: |
          cat > publish/index.html <<EOF
          <!doctype html>
          <html lang="en-us">
            <head>
              <meta charset="utf-8">
              <title>Caterpillar Quest</title>
              <style>
                body { 
                  margin: 0;
                  background: black;
                  display: flex;
                  justify-content: center;
                  align-items: center;
                  height: 100vh;
                }
                #canvas { 
                  max-width: 800px;
                  max-height: 600px;
                  width: 100%;
                  height: 100%;
                }
              </style>
            </head>
            <body>
              <canvas id="canvas"></canvas>
              <script type="text/javascript">
                var Module = {
                  arguments: ['./game.love'],
                  canvas: (function() {
                    var canvas = document.getElementById('canvas');
                    canvas.addEventListener("webglcontextlost", function(e) { 
                      alert('WebGL context lost. You will need to reload the page.'); 
                      e.preventDefault(); 
                    }, false);
                    return canvas;
                  })()
                };
              </script>
              <script async type="text/javascript" src="game.js"></script>
            </body>
          </html>
          EOF

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GH_PAT }}
          publish_dir: ./publish