name: Deploy LOVE2D Game to GitHub Pages with love.js

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Zip game files into game.love
        run: |
          zip -r game.love . -x ".git/*" ".github/*"

      - name: Clone love.js and copy build files
        run: |
          git clone https://github.com/Davidobot/love.js.git
          mkdir lovejs
          cp love.js/build/* lovejs/
          cp love.js/index.html lovejs/

      - name: Prepare publish folder
        run: |
          mkdir publish
          cp game.love publish/
          cp lovejs/* publish/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./publish