name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup
        run: |
          mkdir -p publish
          git clone https://github.com/Davidobot/love.js.git

      - name: Create game.love
        run: zip -r publish/game.love main.lua conf.lua *.png *.wav *.mp3 *.ogg -x ".git/*" ".github/*" "love.js/*"
      
      - name: Setup Emscripten
        uses: mymindstorm/setup-emsdk@v14

      - name: Process love.js src files
        run: |
          # Navigate to love.js directory
          cd love.js
          # Make the build script executable
          chmod +x build_lovejs.sh
          # Run the build script, targeting the game.love file
          ./build_lovejs.sh ../publish/game.love ../publish
          # List the generated files
          ls -la ../publish

      - name: Create index.html
        run: |
          cat > publish/index.html <<EOF
          <!doctype html>
          <html>
            <head>
              <meta charset="utf-8">
              <title>Caterpillar Quest</title>
              <style>body{margin:0;background:#000;display:flex;justify-content:center;align-items:center;height:100vh}</style>
            </head>
            <body>
              <canvas id="canvas" width="1024" height="768"></canvas>
              <script>var Module={canvas:document.getElementById('canvas')};</script>
              <script src="love.js"></script>
            </body>
          </html>
          EOF

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GH_PAT }}
          publish_dir: ./publish