name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Emscripten
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: latest

      - name: Verify Emscripten
        run: |
          emcc --version
          echo "Emscripten cache location: $EM_CACHE"

      - name: Create game.love
        run: |
          mkdir -p build
          zip -r build/game.love main.lua conf.lua *.lua *.png *.jpg *.wav *.mp3 *.ogg -x ".git/*" ".github/*"

      - name: Clone love.js
        run: git clone https://github.com/Davidobot/love.js.git

      - name: Build web version
        run: |
          # Print the build script for debugging
          echo "Content of build_lovejs.sh before modification:"
          cat love.js/build_lovejs.sh
          
          # Fix ALL possible paths to emsdk_env.sh in the script
          sed -i 's|source ../publish/emsdk_env.sh|# Environment already set by GitHub Action|g' love.js/build_lovejs.sh
          sed -i 's|source ../build/web/emsdk_env.sh|# Environment already set by GitHub Action|g' love.js/build_lovejs.sh
          sed -i 's|source .*/emsdk_env.sh|# Environment already set by GitHub Action|g' love.js/build_lovejs.sh
          
          # Print the modified script
          echo "Content of build_lovejs.sh after modification:"
          cat love.js/build_lovejs.sh
          
          # Make the build script executable
          chmod +x love.js/build_lovejs.sh
          
          # Run the build script with our game.love file
          cd love.js
          
          # Export emscripten environment variables explicitly
          export EMSCRIPTEN_ROOT=$EMSDK/upstream/emscripten
          export EM_CONFIG=$HOME/.emscripten
          export EM_CACHE=$HOME/.emscripten_cache
          
          echo "Running build_lovejs.sh with environment:"
          echo "EMSCRIPTEN_ROOT: $EMSCRIPTEN_ROOT"
          echo "EMSDK: $EMSDK"
          
          # Run the script with detailed error output
          ./build_lovejs.sh ../build/game.love ../build/web

      - name: Create custom index.html
        run: |
          cat > build/web/index.html << 'EOF'
          <!doctype html>
          <html lang="en-us">
            <head>
              <meta charset="utf-8">
              <meta name="viewport" content="width=device-width, initial-scale=1">
              <title>Caterpillar Quest</title>
              <style>
                body { 
                  margin: 0;
                  padding: 0;
                  background-color: #000;
                  display: flex;
                  justify-content: center;
                  align-items: center;
                  height: 100vh;
                  overflow: hidden;
                }
                canvas {
                  display: block;
                  max-width: 100%;
                  max-height: 100vh;
                }
              </style>
            </head>
            <body>
              <canvas id="canvas"></canvas>
              <script>
                var Module = {
                  canvas: document.getElementById('canvas'),
                  onRuntimeInitialized: function() {
                    console.log("LÖVE game initialized!");
                  }
                };
              </script>
              <script src="love.js"></script>
            </body>
          </html>
          EOF

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GH_PAT }}
          publish_dir: ./build/web
          force_orphan: true