name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup
        run: |
          mkdir -p publish
          git clone https://github.com/Davidobot/love.js.git

      - name: Create game.love
        run: zip -r publish/game.love main.lua conf.lua *.png *.wav *.mp3 *.ogg -x ".git/*" ".github/*" "love.js/*"
      
      - name: Setup Emscripten
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: 3.1.37  # Specify a version that works with love.js

      - name: Process love.js src files
        run: |
          # Find where emscripten is installed by the GitHub Action
          which emcc
          
          # Create a temporary wrapper script to fix the build process
          cat > build_wrapper.sh <<EOF
          #!/bin/bash
          # Skip the emsdk_env.sh sourcing in the original script
          cd love.js
          sed -i 's|source ../publish/emsdk_env.sh|# Already sourced by GitHub Action|g' build_lovejs.sh
          chmod +x build_lovejs.sh
          ./build_lovejs.sh ../publish/game.love ../publish
          EOF
          
          # Make it executable and run it
          chmod +x build_wrapper.sh
          ./build_wrapper.sh
          
          # List the generated files
          ls -la publish/

      - name: Create index.html
        run: |
          cat > publish/index.html <<EOF
          <!doctype html>
          <html>
            <head>
              <meta charset="utf-8">
              <title>Caterpillar Quest</title>
              <style>body{margin:0;background:#000;display:flex;justify-content:center;align-items:center;height:100vh}</style>
            </head>
            <body>
              <canvas id="canvas" width="1024" height="768"></canvas>
              <script>var Module={canvas:document.getElementById('canvas')};</script>
              <script src="love.js"></script>
            </body>
          </html>
          EOF

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GH_PAT }}
          publish_dir: ./publish