name: Deploy LOVE2D Game to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create publish directory
        run: mkdir publish

      - name: Zip game files into game.love
        run: zip -r publish/game.love . -x ".git/*" ".github/*"

      - name: Clone love.js and list files
        run: |
          git clone https://github.com/Davidobot/love.js.git
          ls -la love.js/

      - name: Copy love.js files
        run: |
          mkdir -p publish
          cp -r love.js/dist/* publish/ || cp -r love.js/build/* publish/ || cp -r love.js/release/* publish/

      - name: Create index.html
        run: |
          cat > publish/index.html <<EOF
          <!doctype html>
          <html lang="en-us">
            <head>
              <meta charset="utf-8">
              <title>Caterpillar Quest</title>
              <style>
                body { margin: 0; background: black; }
                #canvas { 
                  position: absolute;
                  top: 50%;
                  left: 50%;
                  transform: translate(-50%, -50%);
                }
              </style>
            </head>
            <body>
              <canvas id="canvas" oncontextmenu="event.preventDefault()"></canvas>
              <script>
                var Module = {};
                Module.canvas = document.getElementById('canvas');
              </script>
              <script src="game.js"></script>
            </body>
          </html>
          EOF

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GH_PAT }}
          publish_dir: ./publish