name: Deploy LOVE2D Game to GitHub Pages with love.js

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Zip game files into game.love
        run: |
          zip -r game.love . -x ".git/*" ".github/*"

      - name: Download love.js release
        run: |
          mkdir lovejs
          wget https://github.com/TannerRogalsky/love.js/releases/download/11.4-1/love.js -O lovejs/love.js
          wget https://github.com/TannerRogalsky/love.js/releases/download/11.4-1/love.wasm -O lovejs/love.wasm
          wget https://github.com/TannerRogalsky/love.js/releases/download/11.4-1/love.worker.js -O lovejs/love.worker.js
          wget https://github.com/TannerRogalsky/love.js/releases/download/11.4-1/index.html -O lovejs/index.html

      - name: Prepare publish folder
        run: |
          mkdir publish
          cp game.love publish/
          cp lovejs/* publish/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./publish