name: Deploy LOVE2D Game to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create publish directory
        run: mkdir -p publish

      - name: Clone love.js
        run: git clone https://github.com/Davidobot/love.js.git

      - name: Verify love.js files exist
        run: |
          if [ ! -f "love.js/src/game.js" ]; then
            echo "Error: love.js/src/game.js is missing"
            exit 1
          fi
          ls -l love.js/src/game.js

      - name: Copy love.js files
        run: |
          # Copy the engine file
          cp love.js/src/game.js publish/love.js
          # Copy directories if they exist
          if [ -d "love.js/src/compat" ]; then
            cp -r love.js/src/compat publish/
          fi
          if [ -d "love.js/src/release" ]; then
            cp -r love.js/src/release publish/
          fi

      - name: Zip game files into game.love
        run: |
          # Only include game files, not the love.js directory
          zip -r publish/game.love \
            main.lua \
            conf.lua \
            *.png \
            *.wav \
            *.mp3 \
            *.ogg \
            -x "love.js/*" \
            -x ".git/*" \
            -x ".github/*"

      - name: Verify files and sizes
        run: |
          echo "Checking published files:"
          ls -la publish/
          if [ ! -s "publish/love.js" ]; then
            echo "Error: love.js is empty or missing"
            exit 1
          fi
          if [ ! -s "publish/game.love" ]; then
            echo "Error: game.love is empty or missing"
            exit 1
          fi

      - name: Create index.html
        run: |
          cat > publish/index.html <<EOF
          <!doctype html>
          <html lang="en-us">
            <head>
              <meta charset="utf-8">
              <title>Caterpillar Quest</title>
              <style>
                body { 
                  margin: 0;
                  background: black;
                  display: flex;
                  justify-content: center;
                  align-items: center;
                  height: 100vh;
                }
                #canvas { 
                  width: 1024px;
                  height: 768px;
                  max-width: 100%;
                  max-height: 100vh;
                }
              </style>
            </head>
            <body>
              <canvas id="canvas" oncontextmenu="event.preventDefault()"></canvas>
              <script type="text/javascript">
                var Module = {
                  TOTAL_MEMORY: 268435456,
                  noInitialRun: true,
                  canvas: (function() {
                    var canvas = document.getElementById('canvas');
                    canvas.addEventListener("webglcontextlost", function(e) { 
                      alert('WebGL context lost. You will need to reload the page.'); 
                      e.preventDefault(); 
                    }, false);
                    return canvas;
                  })(),
                  print: function(text) { console.log(text); },
                  printErr: function(text) { console.error(text); },
                  postRun: [],
                  arguments: ['./game.love']
                };
              </script>
              <script async type="text/javascript" src="love.js"></script>
              <script>
                console.log('Debug: Module configuration:', Module);
                window.onerror = function(msg, url, line) {
                  console.error('Error:', msg, 'at', url, ':', line);
                };
              </script>
            </body>
          </html>
          EOF

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GH_PAT }}
          publish_dir: ./publish