name: Deploy LOVE2D Game to GitHub Pages with love.js

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Zip game files into game.love
        run: |
          zip -r game.love . -x ".git/*" ".github/*"

      - name: Clone love.js
        run: |
          git clone https://github.com/Davidobot/love.js.git


      - name: List files in love.js/src
        run: |
          ls -l love.js/src/

      - name: Copy love.js files
        run: |
          mkdir lovejs
          cp -r love.js/src/* lovejs/

      - name: Create index.html
        run: |
          cat > lovejs/index.html <<EOF
          <!DOCTYPE html>
          <html>
          <head>
            <meta charset="utf-8">
            <title>LOVE2D Game</title>
          </head>
          <body>
            <script src="game.js"></script>
          </body>
          </html>
          EOF

      - name: Prepare publish folder
        run: |
          mkdir publish
          cp game.love publish/
          cp -r lovejs/* publish/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GH_PAT }}
          publish_dir: ./publish