name: Deploy LOVE2D Game to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create publish directory
        run: mkdir publish

      - name: Zip game files into game.love
        run: zip -r publish/game.love . -x ".git/*" ".github/*"

      - name: Clone love.js
        run: git clone https://github.com/Davidobot/love.js.git

      - name: Copy love.js files
        run: |
          cp -r love.js/src/compat publish/
          cp -r love.js/src/release publish/
          cp love.js/src/game.js publish/

      - name: Create index.html
        run: |
          cat > publish/index.html <<EOF
          <!doctype html>
          <html lang="en-us">
            <head>
              <meta charset="utf-8">
              <title>Caterpillar Quest</title>
              <link rel="icon" type="image/x-icon" href="data:image/x-icon;base64,AAABAAEAEBAQAAEABAAoAQAAFgAAACgAAAAQAAAAIAAAAAEABAAAAAAAgAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" />
              <style>
                body { 
                  margin: 0;
                  background: black;
                  display: flex;
                  justify-content: center;
                  align-items: center;
                  height: 100vh;
                }
                #canvas { 
                  max-width: 100%;
                  max-height: 100%;
                }
              </style>
            </head>
            <body>
              <canvas id="canvas" oncontextmenu="event.preventDefault()"></canvas>
              <script type="text/javascript">
                // Initialize Module before loading game.js
                var Module = {
                  TOTAL_MEMORY: 268435456,
                  arguments: ["./game.love"],
                  printErr: function(text) { console.error(text); },
                  canvas: document.getElementById('canvas'),
                  noInitialRun: true,
                  noExitRuntime: true,
                  preRun: [],
                  postRun: [],
                  print: function(text) { console.log(text); }
                };
              </script>
              <script type="text/javascript" src="release/love.js"></script>
            </body>
          </html>
          EOF

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GH_PAT }}
          publish_dir: ./publish